Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
import numpy as np
array = np.random.randint(1, 101, (3, 3))
print("Original array:")
print(array)
interchanged_array = array.T
print("Interchanged array:")
print(interchanged_array)

Original array:
[[21  5 87]
 [59 82  4]
 [71  3 73]]
Interchanged array:
[[21 59 71]
 [ 5 82  3]
 [87  4 73]]


Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [4]:
import numpy as np
array = np.random.randint(1, 101, 10 )
print("Original array:")
print(array)
array_2x5 = array.reshape(2, 5)
print("Reshaped 2x5 array:")
print(array_2x5)
array_5x2 = array.reshape(5, 2)
print("Reshaped 5x2 array:")
print(array_5x2)

Original array:
[43 27 89 72  3  4 54 79 11 93]
Reshaped 2x5 array:
[[43 27 89 72  3]
 [ 4 54 79 11 93]]
Reshaped 5x2 array:
[[43 27]
 [89 72]
 [ 3  4]
 [54 79]
 [11 93]]


Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [6]:
import numpy as np
array = np.random.rand(4, 4)
print("Original array:")
print(array)
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("Bordered array:")
print(bordered_array)

Original array:
[[0.99156608 0.07408077 0.74680127 0.33117556]
 [0.67454233 0.76836061 0.21023058 0.01430568]
 [0.54824889 0.29683324 0.53276427 0.16559457]
 [0.22059562 0.99289484 0.66860454 0.83734327]]
Bordered array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.99156608 0.07408077 0.74680127 0.33117556 0.        ]
 [0.         0.67454233 0.76836061 0.21023058 0.01430568 0.        ]
 [0.         0.54824889 0.29683324 0.53276427 0.16559457 0.        ]
 [0.         0.22059562 0.99289484 0.66860454 0.83734327 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [8]:
import numpy as np

array = np.arange(10, 31, 5)
print(array)

[10 15 20 25 30]


Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [11]:
import numpy as np
strings = np.array(['python', 'numpy', 'pandas'])
uppercase_strings = [string.upper() for string in strings]
print("Uppercase:", uppercase_strings)
lowercase_strings = [string.lower() for string in strings]
print("Lowercase:", lowercase_strings)
titlecase_strings = [string.title() for string in strings]
print("Titlecase:", titlecase_strings)

Uppercase: ['PYTHON', 'NUMPY', 'PANDAS']
Lowercase: ['python', 'numpy', 'pandas']
Titlecase: ['Python', 'Numpy', 'Pandas']


Q6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [12]:
import numpy as np
words = np.array(["apple", "banana", "cherry"])
spaced_words = np.char.join(" ", words)
print(spaced_words)

['a p p l e' 'b a n a n a' 'c h e r r y']


Q7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [13]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
addition = array1 + array2
print("Addition:\n", addition)
subtraction = array1 - array2
print("Subtraction:\n", subtraction)
multiplication = array1 * array2
print("Multiplication:\n", multiplication)
division = array1 / array2
print("Division:\n", division)

Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [14]:
import numpy as np
identity_matrix = np.eye(5)
diagonal_elements = identity_matrix.diagonal()
print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


Q9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in 
this array.

In [15]:
import numpy as np

def is_prime(num):
  """Checks if a number is prime."""
  if num <= 1:
    return False
  if num <= 3:
    return True
  if num % 2 == 0 or num % 3 == 0:
    return False
  i = 5
  while i * i <= num:
    if num % i == 0 or num % (i + 2) == 0:
      return False
    i += 6
  return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, 100)

# Find prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display prime numbers
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [617, 499, 727, 659, 43, 733, 31, 647, 907, 719, 659, 761, 863, 631, 113, 401, 263]


Q10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly 
averages.

In [16]:
import numpy as np
daily_temperatures = np.array([85, 88, 90, 92, 89, 91, 93, 94, 95, 96, 97, 98, 99, 100, 99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83, 82])
weekly_averages = np.mean(daily_temperatures.reshape(-1, 7), axis=1)
print("Weekly Averages:", weekly_averages)

ValueError: cannot reshape array of size 32 into shape (7)